# Setup
title: Husnu Gokhan Akkurt
tagline: Software Engineer
url: http://blog.gokhanakkurt.com
baseurl: ""
permalink: pretty
paginate: 5

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: "UA-15093494"

# Specify the author for blog posts
author:
  name: Husnu Gokhan Akkurt
  url: https://twitter.com/gokhanakkurt

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/poole/poole
